name: Create Repository Dispatch
on:
  release:
    types:
      released
jobs:
  createRepositoryDispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Determine release train"
        id: yb_train
        run: |
          my_ver=$(cat version.txt)
          git fetch --depth=1 origin master
          main_ver=$(git show origin/master:managed/src/main/resources/version.txt)
          if [[ "$main_ver" == "$my_ver" ]]; then
            train="master"
          else
            if [[ $my_ver =~ ^([0-9]+\.[0-9]+)\.* ]]; then
              train="${BASH_REMATCH[1]}"
            else
              echo "Could not find release version from version.txt"
              exit 1
            fi
          fi
          echo "Release train determined: $train"
          echo "::set-output name=yb_train::${train}"

      - name: "Trigger Repository Dispatch - ZNbase/terraform-gcp-ZNbase"
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" https://api.github.com/repos/ZNbase/terraform-gcp-ZNbase/dispatches \
          --data '{"event_type": "build-on-release", "client_payload":
                   {"prerelease": "${{ github.event.release.prerelease }}",
                    "release": "${{github.event.release.tag_name}}",
                    "yb_release_train": ${{steps.yb_train.outputs.yb_train}} } }'

      - name: "Trigger Repository Dispatch - ZNbase/terraform-aws-ZNbase"
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" https://api.github.com/repos/ZNbase/terraform-aws-ZNbase/dispatches \
          --data '{"event_type": "build-on-release", "client_payload":
                   {"prerelease": "${{ github.event.release.prerelease }}",
                    "release": "${{github.event.release.tag_name}}",
                    "yb_release_train": ${{steps.yb_train.outputs.yb_train}} } }'

      - name: "Trigger Repository Dispatch - ZNbase/terraform-azure-ZNbase"
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" https://api.github.com/repos/ZNbase/terraform-azure-ZNbase/dispatches \
          --data '{"event_type": "build-on-release", "client_payload":
                   {"prerelease": "${{ github.event.release.prerelease }}",
                    "release": "${{github.event.release.tag_name}}",
                    "yb_release_train": ${{steps.yb_train.outputs.yb_train}} } }'

      - name: "Trigger Repository Dispatch - ZNbase/azure-resource-manager"
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" https://api.github.com/repos/ZNbase/azure-resource-manager/dispatches \
          --data '{"event_type": "build-on-release", "client_payload":
                   {"prerelease": "${{ github.event.release.prerelease }}",
                    "release": "${{github.event.release.tag_name}}",
                    "yb_release_train": ${{steps.yb_train.outputs.yb_train}} } }'

      - name: "Trigger Repository Dispatch - ZNbase/gcp-deployment-manager"
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" https://api.github.com/repos/ZNbase/gcp-deployment-manager/dispatches \
          --data '{"event_type": "build-on-release", "client_payload":
                   {"prerelease": "${{ github.event.release.prerelease }}",
                    "release": "${{github.event.release.tag_name}}",
                    "yb_release_train": ${{steps.yb_train.outputs.yb_train}} } }'

      - name: "Trigger Repository Dispatch - ZNbase/aws-cloudformation"
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" https://api.github.com/repos/ZNbase/aws-cloudformation/dispatches \
          --data '{"event_type": "build-on-release", "client_payload":
                   {"prerelease": "${{ github.event.release.prerelease }}",
                    "release": "${{github.event.release.tag_name}}",
                    "yb_release_train": ${{steps.yb_train.outputs.yb_train}} } }'

      - name: "Trigger Repository Dispatch - ZNbase/homebrew-ZNbasedb"
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" https://api.github.com/repos/ZNbase/homebrew-ZNbasedb/dispatches \
          --data '{"event_type": "update-on-release", "client_payload":
                   {"prerelease": "${{ github.event.release.prerelease }}",
                    "release": "${{github.event.release.tag_name}}",
                    "yb_release_train": ${{steps.yb_train.outputs.yb_train}} } }'

      - name: "Trigger Repository Dispatch - ZNbase/utilities"
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" https://api.github.com/repos/ZNbase/utilities/dispatches \
          --data '{"event_type": "build-on-release", "client_payload":
                   {"prerelease": "${{ github.event.release.prerelease }}",
                    "release": "${{github.event.release.tag_name}}",
                    "yb_release_train": ${{steps.yb_train.outputs.yb_train}} } }'

      - name: "Trigger Repository Dispatch - ZNbase/charts"
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" https://api.github.com/repos/ZNbase/charts/dispatches \
          --data '{"event_type": "update-on-release", "client_payload":
                   {"prerelease": "${{ github.event.release.prerelease }}",
                    "release": "${{github.event.release.tag_name}}",
                    "yb_release_train": ${{steps.yb_train.outputs.yb_train}} } }'

      - name: "Trigger Repository Dispatch - ZNbase/ZNbase-db-action"
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" https://api.github.com/repos/ZNbase/ZNbase-db-action/dispatches \
          --data '{"event_type": "on-release"}'

      - name: "Trigger Repository Dispatch - ZNbase/ZNbase-operator"
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" https://api.github.com/repos/ZNbase/ZNbase-operator/dispatches \
          --data '{"event_type": "update-on-release",  "client_payload": {"prerelease": "${{ github.event.release.prerelease }}", "release": "${{github.event.release.tag_name}}"  }}'
